version: '3.4'

services:
  dockerdemo2:
    image: dockerdemo2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8085:8085
      - 5005:5005
